name: livi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  pie_chart: ^5.0.0
  
  path_provider: ^2.1.2   # للوصول إلى مسارات الجهاز
  open_file: ^3.3.2       # لفتح الملفات بعد حفظها
  pdf: ^3.10.7            # لإنشاء ملفات PDF
  file_picker: ^6.1.1     # لاختيار مكان حفظ الملف (اختياري

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png





